spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hrbank
    username: postgres
    password: 970501
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
